<a href="https://colab.research.google.com/github/nishusingh11/python-scripting-for-social-science/blob/main/midterm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Part 1 Containers

You must execute the next cell, which we will refer to as the **data cell**, to do the problems in this section.

In [ ]:
# Data cell

epsilon_left = 'abcde'
epsilon_right = 'zyxwv'
epsilon = list(zip(epsilon_right,epsilon_left))
fruit = ['tomato','cabbage','rambutan','persimmon','mangosteen']
frittata = {'alpha': epsilon_right + epsilon_left,
            'beta': epsilon_left + epsilon_right,
            'delta': fruit,
            'gamma': dict(epsilon)}

Using the containers in the data cell, write a single Python expression (so, **not** a for-loop) which returns the given values.  Sometimes there are actually many possible answers.  Try for the simplest.

In [ ]:
# Checking
epsilon_left

'abcde'

In [ ]:
# Checking
epsilon_right

'zyxwv'

In [ ]:
# Checking
epsilon

[('z', 'a'), ('y', 'b'), ('x', 'c'), ('w', 'd'), ('v', 'e')]

In [ ]:
# Checking
fruit

['tomato', 'cabbage', 'rambutan', 'persimmon', 'mangosteen']

In [ ]:
# Checking
frittata

{'alpha': 'zyxwvabcde',
 'beta': 'abcdezyxwv',
 'delta': ['tomato', 'cabbage', 'rambutan', 'persimmon', 'mangosteen'],
 'gamma': {'v': 'e', 'w': 'd', 'x': 'c', 'y': 'b', 'z': 'a'}}

# 1.1

Return `'de'`.

In [ ]:
# Answer 1.1
# epsilon_left = 'abcde'
epsilon_left[3:]            # Accessing 'de' using splice.

'de'

# 1.2

Return `'wvab'`.

In [ ]:
# Answer 1.2
# frittata is the dictionary, where 'alpha' is the key and alpha is containing string.
# 'alpha': 'zyxwvabcde'

frittata['alpha'][3:7]              # Accessing 'wvab' using splice.

'wvab'

# 1.3

Return `'rambutan'`.

In [ ]:
# Answer 1.3
# fruit is the list whic is contatinig collection of strings.
fruit[2]                            # 'rambutan' is stored at 2nd index.

'rambutan'

# 1.4

Return `'sim'`.

In [ ]:
# Answer 1.4
# fruit is the list whic is contatinig collection of strings.
fruit[3][3:6]                        # splicing 'sim' from word 'persimmon' which is stored at index 3rd.

'sim'

# 1.5

Return {'z': 'a', 'y': 'b', 'x': 'c', 'w': 'd', 'v': 'e'}

In [ ]:
# checking 
{'z': 'a', 'y': 'b', 'x': 'c', 'w': 'd', 'v': 'e'} == frittata['gamma']

True

In [ ]:
# Answer 1.5
# frittata['gamma'] is containing the nested dictionary.
frittata['gamma']                  # Above cell showing both are same. 

{'v': 'e', 'w': 'd', 'x': 'c', 'y': 'b', 'z': 'a'}

# 1.6

Return 

`[('x', 'c'), ('w', 'd')]`

In [ ]:
# Answer 1.6
# epsilon is the list of tuples.
epsilon[2:4]                        # Accessing by splicing.

[('x', 'c'), ('w', 'd')]

# 1.7

Compare the results in the next two cells.

Explain why one expression raises an `Exception` and the other does not, even
though both involve accessing data defined in `epsilon`.

In [ ]:
# Given
epsilon['x']

TypeError: ignored

In [ ]:
# Given
frittata['gamma']['x']

'c'

[Answer 1.7]

In first cell, epsilon is the list of tuple, each tuple is containing the 2 letters. We can only access the list by index and index must be integer.

In second cell, frittata is the dictionary object and frittata['gamma'] is nestesd dictionary. frittata['gamma']['x'] means we are accessing the value stored at key 'x' which is 'c'.


# Part 2 Functions, Loops

You must execute the data cell to do the problems in this section.

In [ ]:
# Data cell

import numpy as np

xx = np.arange(0,26,4)

sad_story = """Billy the Kid lived in the Wild West long ago .
He was an outlaw .
He was friends with Pat Garrett who was a lawman .
One day Pat Garrett had to bring Billy the Kid in .
Billy would not come .
They had a gunfight and Pat shot his friend Billy .
"""

# 2.1

Write a loop (it can be a list comprehension) that computes a list of the numbers in `xx` that arew divisible by 3.

Do not import any python packages to help (that would suggest that you have
not been doing the material in the first part of the class and have done a google search to solve this problem).

You may find it useful to be reminded of the `%`-operator:

x%y

returns the remainder when x is divided by y.  So, for example,

```
>>> 17%5
2
```

Note: although `xx` is a numpy array, for the purposes of this section you
may treat it as if it were a list.

In [ ]:
# Checking
xx

array([ 0,  4,  8, 12, 16, 20, 24])

In [ ]:
# Answer 2.1
# Creating list by list comprehension that computing the list of numbers in xx that are divisible by 3 (using modulus operator).
list1 = [num for num in xx if num % 3 == 0]        # storing list in list1 variable
list1                                             # Printing list1

[0, 12, 24]

# 2.2

Write a for-loop (it may be a list comprehension) that builds a list containing all instances of the letter  `t` in `sad_story`

In [ ]:
# Answer 2.2
# Creating list by list comprehension that will contain all the instatnces of letter t in sad_story.
list2 = [ char for char in sad_story if char == 't']
list2             # length of list2 is 17

['t',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't']

# 2.3

Write a for-loop (it may be a list comprehension) that builds a list containing all instances of the word  `the` in `sad_story`.

In [ ]:
# creating new_list which will contain the all the words in sad_story using split().
new_list = sad_story.split()

In [ ]:
# Answer 2.3
# list3 the output list which will contain the all the instances of the word 'the' present in sad_story.
list3 = [word for word in new_list if word == "the"]
list3           # length of the list3 is 3

['the', 'the', 'the']

# 2.4

Write a for loop that creates a dictionary containing the counts of all the words
in `sad_story`.  Do not import any Python modules. 

Call your dictonary `wd_cts`.  If your program is correct `wd_cts`
should contain the following count:

```
>>> wd_counts['in']
2
```

In [ ]:
# Answer 2.4
wd_counts = {}                           # creating empty dictionary.
for word in new_list:                    # looping through new_list to calculate the frequency of each word present in sad_story.
    if word not in wd_counts:
        wd_counts[word] = 1
    else:
        wd_counts[word] += 1
wd_counts                                # Printing the resultant dictionary

{'.': 6,
 'Billy': 4,
 'Garrett': 2,
 'He': 2,
 'Kid': 2,
 'One': 1,
 'Pat': 3,
 'They': 1,
 'West': 1,
 'Wild': 1,
 'a': 2,
 'ago': 1,
 'an': 1,
 'and': 1,
 'bring': 1,
 'come': 1,
 'day': 1,
 'friend': 1,
 'friends': 1,
 'gunfight': 1,
 'had': 2,
 'his': 1,
 'in': 2,
 'lawman': 1,
 'lived': 1,
 'long': 1,
 'not': 1,
 'outlaw': 1,
 'shot': 1,
 'the': 3,
 'to': 1,
 'was': 3,
 'who': 1,
 'with': 1,
 'would': 1}

# 2.5

Write a **function** `find_word_forms` that takes a string `text_str` and a word `form` as its **two** arguments and returns all **words** in `text_str` that end with `form`.
Write this without importing any Python modules.

Here are some tests that your function should pass:

```
>>> find_word_forms(sad_story, 'ing')
['bring']
>>> find_word_forms(sad_story, 'ed')
['lived']
>>> find_word_forms("He 's sending birds on the wing .", 'ing')
['sending', 'wing']
>>> find_word_forms(sad_story, 'g')
['long', 'bring']
```

Hint:  You may find it helpful to remember the
string method `endswith`.

In [ ]:
# Answer 2.5
def find_word_forms(text_str, form):                 #  Implementing function find_word_forms(text_str, form) to check whether the the words in text_str is end with form.
    result = []                                      # creating empty list name result.
    for word in text_str.split():                    # Loop through each word present in text_str.
        if word.endswith(form):                      # using endswith() to check whether the word is end woth form or not.
            result.append(word)                      # If yes then append the word in result
    return result                                    # return the result.


In [ ]:
# Testing
find_word_forms(sad_story, 'ing')

['bring']

In [ ]:
# Testing
find_word_forms(sad_story, 'ed')

['lived']

In [ ]:
# Testing
find_word_forms("He 's sending birds on the wing .", 'ing')

['sending', 'wing']

In [ ]:
# Testing
find_word_forms(sad_story, 'g')

['long', 'bring']

# 2.6

Write a function that converts degrees to radians. You are allowed
to use the following import statement:

```
from numpy import pi
```

The formula is

```
Radians = (Degrees/360) * 2 * pi
```

Here are some tests

```
>>> deg2rad(360)
6.283185307179586
>>> deg2rad(90)
1.5707963267948966
>>> deg2rad(72)
1.2566370614359172
```

In [ ]:
# Answer 2.6
from numpy import pi                     # Importing the pi module in numpy
def deg2rad(degree):                     # creating function definition deg2rad(degree) which takes degree as input
    radians = (degree/360) * 2 * pi      # formula to convert the degree into radians
    return radians                       # Return the radians

In [ ]:
# Testing
deg2rad(360)

6.283185307179586

In [ ]:
# Testing
deg2rad(90)

1.5707963267948966

In [ ]:
# Testing
deg2rad(72)

1.2566370614359172

# Part 3 Numpy arrays

You must execute the next cell to do the problems in this section.

In [ ]:
# Data cell

import numpy as np

xx = np.arange(4,61,4)

yy = xx.reshape((3,5))

# 3.1

Write a single Python expression that returns 12 from `xx`

In [ ]:
# Checking
xx

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

In [ ]:
# Checking
yy

array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40],
       [44, 48, 52, 56, 60]])

In [ ]:
# Answer 3.1
xx[2]    # 12 is stored at 2nd index in xx object

12

# 3.2

Write a single Python expression  that returns all members of `xx` divisible by 8.
Hint: Use a splice.

In [ ]:
# Answer 3.2
xx[1::2]      # Using splice: Divisible by 8 is stored at every alternate index in xx.

array([ 8, 16, 24, 32, 40, 48, 56])

# 3.3

Write a single Python expression  that returns all members of `xx` 
greater than 16.  You may use a splice if you wish.

In [ ]:
# Answer 3.3
xx[4:]         # using splice returning the numbers which are greater than 16.

array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

# 3.4

Write a single Python expression  that returns the following
1D array from `yy`.

```
array([24, 28, 32, 36, 40])
```

In [ ]:
# Answer 3.4
yy[1,:]      # returning 1d array from yy

array([24, 28, 32, 36, 40])

# 3.5

Write a single Python expression  that returns the following
2D array from `yy`.

```
array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40]])
```

In [ ]:
# Answer 3.5
yy[:2,:]           # returning above 2d array from yy.

array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40]])

# 3.6

Write a single Python expression  that returns the following
2D array from `yy`.

```
array([[32, 36],
       [52, 56]])
```

In [ ]:
# Answer 3.6
yy[1:3,2:4]          # Returning above 2d array from yy.

array([[32, 36],
       [52, 56]])

# Part 4  Wine Data

In this exercise set, we load wine data. This is a multi class dataset that has data for three different wine types  (stored in `target` below) corresponding to three
different cultivators in a particular region of Italy.  These will just
be referred to as class_1 calss_2 and class_3 in the description below
and in the questions.
The chemical properties of the wine stored in the 2D numpy array `data` below are sufficient to identity the cultivator, but it's a challenging classification problem.

Wine recognition dataset
-----------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
     
    The wine atributes listed in their column order.
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners: 

Forina, M. et al, PARVUS - 
An Extendible Package for Data Exploration, Classification and Correlation. 
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science. 

You must evaluate the next cell to do the problems in this section.

In [ ]:
# Data Cell

from sklearn.datasets import load_wine
wdata = load_wine()
data = wdata.data
target = wdata.target

In [ ]:
# To check
wdata

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

**4.0**  

Write a Python expression that returns s Boolean array defining
the set of rows of the `data` array with magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [ ]:
# Boolean array defining the set of rows of the data array with magnesium level greater than 99.7. This is not the answer.
data1 = data[:,4] > 99.7      
data1

array([ True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True, False, False, False,  True,  True,  True, False,
       False,  True,  True, False, False,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
        True, False, False, False,  True,  True, False, False, False,
       False, False,

In [ ]:
# Boolean array defining the set of rows of the data array with Proanthocyanins level less than 1.59. This is not the answer.
data2 = data[:,8] < 1.59
data2

array([False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False, False, False,  True, False, False,  True,
        True, False, False, False, False, False,  True,  True, False,
        True,  True,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
       False,  True, False, False,  True,  True, False,  True, False,
        True, False, False,  True,  True,  True, False, False,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True, False, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False,  True,  True,  True,  True, False,  True,
       False,  True, False, False, False, False, False, False,  True,
       False, False,

In [ ]:
# Answer 4.0
result0 = data1 & data2   
result0           # shape (178,)

array([False,  True, False, False, False, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

**4.1**

Write a Python expression that returns the rows of the `data` array 
representing  wine samples with  magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [ ]:
# Answer 4.1
result1 = data[data1 & data2]        # shape (35, 13)
result1

array([[1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.406e+01, 2.150e+00, 2.610e+00, 1.760e+01, 1.210e+02, 2.600e+00,
        2.510e+00, 3.100e-01, 1.250e+00, 5.050e+00, 1.060e+00, 3.580e+00,
        1.295e+03],
       [1.363e+01, 1.810e+00, 2.700e+00, 1.720e+01, 1.120e+02, 2.850e+00,
        2.910e+00, 3.000e-01, 1.460e+00, 7.300e+00, 1.280e+00, 2.880e+00,
        1.310e+03],
       [1.376e+01, 1.530e+00, 2.700e+00, 1.950e+01, 1.320e+02, 2.950e+00,
        2.740e+00, 5.000e-01, 1.350e+00, 5.400e+00, 1.250e+00, 3.000e+00,
        1.235e+03],
       [1.351e+01, 1.800e+00, 2.650e+00, 1.900e+01, 1.100e+02, 2.350e+00,
        2.530e+00, 2.900e-01, 1.540e+00, 4.200e+00, 1.100e+00, 2.870e+00,
        1.095e+03],
       [1.328e+01, 1.640e+00, 2.840e+00, 1.550e+01, 1.100e+02, 2.600e+00,
        2.680e+00, 3.400e-01, 1.360e+00, 4.600e+00, 1.090e+00, 2.780e+00,
        8.80

**4.2**

How many such rows are there?  Show the computation.

In [ ]:
# Answer 4.2 
len(result1)   # In above cell computed the rows of the data array representing wine samples with magnesium level greater than 99.7 and Proanthocyanins level less than 1.59. In this cell printing the no. of rows created in above cell.

35

**4.3**

Write a Python expression that returns the rows of the `data` array 
representing wine samples such that they are not of class_1 and they
have magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [ ]:
# Storing the boolean array such that they are not of class_1. 
data3 = target != 1      
data3                      # This is not the answer.

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [ ]:
# Answer 4.3
# Returns the rows of the data array representing wine samples such that they are not of class_1 and they have magnesium level greater than 99.7 and Proanthocyanins level less than 1.59
result3 = data[data1 & data2 & data3]      # data1: return the boolean array which satisfied magnesium level greater than 99.7
                                           # data2: returns boolean array which satisfied Proanthocyanins level less than 1.59
                                           # data3: returns the boolean array such that they are not of class_1.
result3                  # shape (27, 13)

array([[1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.406e+01, 2.150e+00, 2.610e+00, 1.760e+01, 1.210e+02, 2.600e+00,
        2.510e+00, 3.100e-01, 1.250e+00, 5.050e+00, 1.060e+00, 3.580e+00,
        1.295e+03],
       [1.363e+01, 1.810e+00, 2.700e+00, 1.720e+01, 1.120e+02, 2.850e+00,
        2.910e+00, 3.000e-01, 1.460e+00, 7.300e+00, 1.280e+00, 2.880e+00,
        1.310e+03],
       [1.376e+01, 1.530e+00, 2.700e+00, 1.950e+01, 1.320e+02, 2.950e+00,
        2.740e+00, 5.000e-01, 1.350e+00, 5.400e+00, 1.250e+00, 3.000e+00,
        1.235e+03],
       [1.351e+01, 1.800e+00, 2.650e+00, 1.900e+01, 1.100e+02, 2.350e+00,
        2.530e+00, 2.900e-01, 1.540e+00, 4.200e+00, 1.100e+00, 2.870e+00,
        1.095e+03],
       [1.328e+01, 1.640e+00, 2.840e+00, 1.550e+01, 1.100e+02, 2.600e+00,
        2.680e+00, 3.400e-01, 1.360e+00, 4.600e+00, 1.090e+00, 2.780e+00,
        8.80

**4.4**

How many such rows are there?  Show the computation.

In [ ]:
# Answer 4.4
len(result3)      # Returns the number of rows created in above cell.

27